import { timedFetch } from './timed-fetch';
import * as SecureStore from 'expo-secure-store';
import * as AuthSession from 'expo-auth-session';
import { Platform } from 'react-native';
import { apiUrl, loadApiSettings } from '../constants/api';

export interface Session { provider?: 'local' | 'oidc'; accessToken: string; refreshToken?: string; expiresAt: number;
  user: { user_id: string; name: string; phone: string; role: string }; }
let current: Session | null = null;
let refresh: Promise<string | undefined> | null = null;
const KEY = 'suraksha.session.v1';
const options = { keychainAccessible: SecureStore.AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY };
export const oidcIssuer = process.env.EXPO_PUBLIC_OIDC_ISSUER || '';
export const oidcClient = process.env.EXPO_PUBLIC_OIDC_CLIENT_ID || '';

async function save(session: Session) {
  current = session;
  if (Platform.OS !== 'web') await SecureStore.setItemAsync(KEY, JSON.stringify(session), options);
}
export async function loadSession(): Promise<Session | null> {
  await loadApiSettings();
  if (!current && Platform.OS !== 'web') {
    const raw = await SecureStore.getItemAsync(KEY, options);
    if (raw && !current) current = JSON.parse(raw) as Session;
  }
  return current;
}
export async function establishSession(accessToken: string, refreshToken?: string, expiresIn = 3600, provider: 'local' | 'oidc' = 'oidc'): Promise<Session> {
  await loadApiSettings();
  const response = await timedFetch(apiUrl('/api/v1/identity/me'), { headers: { Authorization: `Bearer ${accessToken}` } });
  if (response.status === 404) throw new Error('This backend is missing /api/v1/identity/me. Update suraksha-backend from GitHub before signing in.');
  if (!response.ok) throw new Error(`Sign-in failed (HTTP ${response.status}). Use an unexpired token generated by this backend and check its authentication settings.`);
  const user: Session['user'] = await response.json();
  const session = { provider, accessToken, refreshToken, user, expiresAt: Date.now() + expiresIn * 1000 };
  await save(session);
  return session;
}
export async function sessionToken(): Promise<string | undefined> {
  const session = await loadSession();
  if (!session) return undefined;
  if (session.expiresAt > Date.now() + 60000) return session.accessToken;
  if (!session.refreshToken) return session.accessToken;
  if (session.provider !== 'local' && (!oidcIssuer || !oidcClient)) return session.accessToken;
  if (!refresh) refresh = (async () => {
    if (session.provider === 'local') {
      const response = await timedFetch(apiUrl('/api/v1/accounts/refresh'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: session.refreshToken }) });
      if (!response.ok) throw new Error(response.status === 401 ? 'Session revoked. Sign out and sign in again.' : 'Unable to renew sign-in. Reconnect to the backend.');
      const tokens = await response.json();
      // Do not restore a session if the user signed out while refresh was running.
      if (current !== session) return undefined;
      await save({ ...session, accessToken: tokens.access_token, expiresAt: Date.now() + tokens.expires_in * 1000 });
      return tokens.access_token as string;
    }
    const discovery = await AuthSession.fetchDiscoveryAsync(oidcIssuer);
    const tokens = await AuthSession.refreshAsync({ clientId: oidcClient, refreshToken: session.refreshToken }, discovery);
    if (current !== session) return undefined;
    await save({ ...session, accessToken: tokens.accessToken, refreshToken: tokens.refreshToken ?? session.refreshToken,
      expiresAt: Date.now() + (tokens.expiresIn ?? 3600) * 1000 });
    return tokens.accessToken;
  })().finally(() => { refresh = null; });
  return refresh;
}
export async function signOut(): Promise<void> {
  const old = await loadSession();
  // Revoke online when possible; local sign-out always removes credentials.
  if (old?.provider === 'local' && old.refreshToken) {
    try { await timedFetch(apiUrl('/api/v1/accounts/logout'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refresh_token: old.refreshToken }) }); } catch { /* Server-side session can be revoked by the operator if offline. */ }
  }
  current = null;
  if (Platform.OS !== 'web') await SecureStore.deleteItemAsync(KEY, options);
}

export async function passwordSignIn(email: string, password: string, registration?: { name: string; phone: string }): Promise<Session> {
  await loadApiSettings();
  const response = await timedFetch(apiUrl(`/api/v1/accounts/${registration ? 'register' : 'login'}`), {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: email.trim(), password, ...registration }),
  });
  const data = await response.json();
  if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : 'Check your email, password (at least 12 characters), name and phone number.');
  return establishSession(data.access_token, data.refresh_token, data.expires_in, 'local');
}
